Repository IntelAI/vck, pull requests merged in 2018-05, with the labels that each got.

#37 Delete the data when CR is deleted.
  docs/user.md
  pkg/handlers/handlers.go
  pkg/handlers/nfs_handler.go
  pkg/handlers/s3_dev_handler.go
  pkg/handlers/s3_handler.go
  pkg/hooks/hooks.go
  pkg/hooks/hooks_test.go
  pkg/templates/pod.tmpl
Labels: size/L

#40 Adding tolerations and nodeaffinity
  docs/arch.md
  pkg/apis/kvc/v1/types.go
  pkg/hooks/hooks.go
  pkg/templates/pod.tmpl
  resources/customresources/s3/minio.yaml
  resources/customresources/s3/one-vc-multiple-replicas.yaml
  resources/customresources/s3/one-vc.yaml
  resources/customresources/s3/two-vc.yaml
Labels: needs-ok-to-test, size/L

#44 Fix 'make code-generation' error
  hack/update-codegen.sh
Labels: needs-ok-to-test, size/XS

#45 Update user docs for using valid server and path during PVC creation
  docs/user.md
Labels: needs-ok-to-test, size/XS

#47 Added overview figure
  README.md
  docs/images/kvc.png
Labels: size/XS

#41 Append Pod logs to CR in case of data download failure
  helm-charts/kube-volume-controller/templates/rbac.yaml
  pkg/handlers/s3_handler.go
  test/e2e/kvc_test.go
Labels: needs-ok-to-test, size/M

#35 Adding pachyderm handler
  Gopkg.lock
  docker/build
  docker/pachyderm/Dockerfile
  docker/push
  docs/arch.md
  docs/user.md
  helm-charts/kube-volume-controller/values.yaml
  main.go
  pkg/handlers/handler_test.go
  pkg/handlers/pachyderm_handler.go
  pkg/templates/pod_pachyderm.tmpl
  resources/customresources/pachyderm/one-vc.yaml
  test/e2e/kvc_test.go
Labels: needs-ok-to-test, size/XL
